version: '3'
services:
  bot:
    image: lionezajoao/conta-falta:latest
    container_name: conta-falta
    restart: on-failure
    env_file:
      - .env
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_BASE_DATABASE}
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_PORT=${PG_PORT}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
