version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-absence-bot
    restart: on-failure
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      alembic upgrade head && 
      python -m app.main
      "


  postgres:
    image: postgres:15
    container_name: telegram-absence-postgres
    restart: on-failure
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5